services:
  redis:
    image: "redis:alpine"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A tasks worker --loglevel=INFO"
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - .:/app

  runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - celery
    command: "python tasks.py"
    volumes:
      - .:/app